add read the docs yaml
ploomber/sql pull request #4
Opened 2023-05-30 22:51 UTC by lfunderburk

2023-05-30 23:21 UTC, edublancas requested changes

2023-05-30 23:21 UTC, edublancas commented on readthedocs.yml
> +  environment: doc/environment.lock.yml
you're missing this file

2023-05-31 16:17 UTC, lfunderburk commented on readthedocs.yml
> +      - cat environment.lock.yml
removed

2023-05-31 16:38 UTC, lfunderburk commented on readthedocs.yml
> +  environment: doc/environment.lock.yml
resolved in latest commit

2023-05-31 17:04 UTC, edublancas approved these changes
if you have issues with the lock file (I've had issues in the past), you can generate a regular environment.yml (with no pinned dependencies)

2023-05-31 17:04 UTC, merged