First draft of "Types of Data Visualizations" Section
ploomber/sql pull request #48
Opened 2023-06-27 20:05 UTC by jpjon

## Describe your changes

## Issue number
#41
Closes #41 

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)

2023-06-29 22:21 UTC, lfunderburk commented
Hi @jpjon 

Please fix existing conflicts due to the change in structure in main

Moving this from blocked to doing

2023-06-30 01:27 UTC, jpjon commented
Main branch has been merged and is ready for review.

2023-06-30 01:40 UTC, TegveerG submitted a review, later dismissed
Looks good to me, nice work!

2023-06-30 06:48 UTC, lfunderburk requested changes
Hi @jpjon 

It might be confusing for the audience to start creating datasets from scratch. 

It will also cause confusion since the seaborn and plotly tutorials are using the 2 schemas we've been working with. 

Also noticing that half of this tutorial revolves around the creation of the data. It distracts a bit from the main topic. 

Thinking back on discussion, I think it makes sense to stick with one of the tables in the datasets to keep this intro simple.

To keep things easy, maybe you can reuse some of the queries from the getting started section.

2023-07-03 17:19 UTC, jpjon commented
The section has been revised based on Laura's suggestions. Should be ready for review!

2023-07-05 11:06 UTC, neelasha23 commented on docs/visualizing-your-sql-queries/types-of-visualizations.md
> +This module will teach you the `seaborn` and `plotly` packages. Before we get into the details of each package, we first introduce the common types of data visualization with one of the most basic vi
`In this module we will learn about...`

2023-07-05 11:15 UTC, neelasha23 commented on docs/visualizing-your-sql-queries/types-of-visualizations.md
> +The second in the above code cell is really all we need to create a baseline bar plot. The remaining lines are supplemental elements that labels and customizes the y-axis, x-axis, size, and title of
second what?

2023-07-05 11:17 UTC, neelasha23 commented on docs/visualizing-your-sql-queries/types-of-visualizations.md
> +We can easily see that "management" and "blue-collar" jobs are the most prominent job category in this data set. Box plots are a great option when you need to visualize distributions of groups in a c
Please highlight management and blue-collar jobs using ``

2023-07-05 15:56 UTC, jpjon commented
Thank you for the suggestions @neelasha23. They have been implemented and the PR is ready for review.

2023-07-06 05:22 UTC, neelasha23 approved these changes
lg!
Please tick the checklist boxes when opening a PR

2023-07-06 16:00 UTC, merged